# This metric provides byte-rate ingress traffic per source and destination workload, with availability zones
# The processor feature "addZone" must be enabled.
# More examples in https://github.com/netobserv/network-observability-operator/tree/main/config/samples/flowmetrics
apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: az-aware-workloads-traffic
spec:
  metricName: az_aware_workloads_traffic_bytes_total
  type: Counter
  valueField: Bytes
  direction: Ingress
  labels: 
  - DstK8S_Namespace
  - DstK8S_OwnerName
  - DstK8S_OwnerType
  - DstK8S_Zone
  - SrcK8S_Namespace
  - SrcK8S_OwnerName
  - SrcK8S_OwnerType
  - SrcK8S_Zone
