apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: flowmetric-pods-talking-outside
spec:
  metricName: pods_talking_outside_bytes_total
  type: Counter
  valueField: Bytes
  direction: Egress
  labels: [SrcK8S_Name,SrcK8S_Namespace,SrcK8S_OwnerName,SrcK8S_OwnerType,DstAddr]
  filters:
  - field: DstK8S_OwnerType
    matchType: Absence
  - field: SrcK8S_Type
    value: Pod
