# This metric provides a count of flows per destination ports smaller than 1029 (feel free to edit the regex to better suit your needs), with source and destination workloads
# More examples in https://github.com/netobserv/network-observability-operator/tree/main/config/samples/flowmetrics
apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: flowmetric-workload-root-ports
spec:
  metricName: workload_root_port_flows_total
  type: Counter
  labels: [DstPort,SrcK8S_Namespace,SrcK8S_OwnerName,SrcK8S_OwnerType,DstK8S_Namespace,DstK8S_OwnerName,DstK8S_OwnerType]
  filters:
  - field: DstPort
    value: "^10[0-2]?\\d?$|^\\d?\\d?\\d?$"
    matchType: MatchRegex
