# This metric provides byte-rate per service and port. It also provides a dashboard chart.
# More examples in https://github.com/netobserv/network-observability-operator/tree/main/config/samples/flowmetrics
apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: flowmetric-service-traffic
spec:
  metricName: service_bytes_total
  type: Counter
  valueField: Bytes
  labels: [DstK8S_Name,DstK8S_Namespace,DstPort,SrcK8S_OwnerName,SrcK8S_OwnerType,SrcK8S_Namespace]
  filters:
  - field: DstK8S_Type
    value: Service
  charts:
  - dashboardName: Main
    sectionName: Services
    title: Top traffic per service and port
    unit: Bps
    type: StackArea
    queries:
    - promQL: "sum(rate($METRIC[2m])) by (DstK8S_Namespace, DstK8S_Name, DstPort)"
      legend: "{{DstK8S_Namespace}} / {{DstK8S_Name}} ({{DstPort}})"
