
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-flows-netobserv-io-v1beta2-flowcollector
  failurePolicy: Fail
  name: flowcollectorconversionwebhook.netobserv.io
  rules:
  - apiGroups:
    - flows.netobserv.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - flowcollectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-flows-netobserv-io-v1alpha1-flowmetric
  failurePolicy: Fail
  name: flowmetricvalidationwebhook.netobserv.io
  rules:
  - apiGroups:
    - flows.netobserv.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flowmetrics
  sideEffects: None
