# permissions for end users to edit flowmetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: flowmetric-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netobserv-operator
    app.kubernetes.io/part-of: netobserv-operator
    app.kubernetes.io/managed-by: kustomize
  name: flowmetric-editor-role
rules:
- apiGroups:
  - flows.netobserv.io
  resources:
  - flowmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flows.netobserv.io
  resources:
  - flowmetrics/status
  verbs:
  - get
