# Check that the 0 container is the expected one
- op: test
  path: /spec/template/spec/containers/0/name
  value: manager

- op: add
  path: "/spec/template/spec/volumes/-"
  value:
    name: manager-metric-tls
    secret:
      secretName: manager-metrics-tls
      defaultMode: 420

- op: add
  path: "/spec/template/spec/containers/0/volumeMounts/-"
  value:
    name: manager-metric-tls
    readOnly: true
    mountPath: /etc/tls/private

- op: add
  path: "/spec/template/spec/containers/0/args/-"
  value: '--metrics-cert-file=/etc/tls/private/tls.crt'

- op: add
  path: "/spec/template/spec/containers/0/args/-"
  value: '--metrics-cert-key-file=/etc/tls/private/tls.key'
