name: pull request checks

on:
  pull_request:
    branches: ['*']

jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.23']
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: set up go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v3
    - name: check format
      run: make fmt && git add -A && git diff --exit-code
    - name: build, lint, test
      run: make build lint test
    - name: check clean vendors
      run: go mod vendor
    - name: Report coverage
      if: ${{ matrix.go == '1.23' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./cover.out
        flags: unittests
        fail_ci_if_error: false
        verbose: true

  bundle-check:
    runs-on: ubuntu-latest
    name: Checking bundle up-to-date
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: checkout
      uses: actions/checkout@v3
    - name: generate bundle
      run: make update-bundle
    - name: check bundle clean state
      run: git add -A && git diff HEAD -I "operator-sdk-v" --exit-code

  helm-check:
    runs-on: ubuntu-latest
    name: Checking helm up-to-date
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: checkout
      uses: actions/checkout@v3
    - name: check helm clean state
      run: |
        mkdir _tmp || true
        yq '.spec.install.spec.deployments[0].spec' bundle/manifests/netobserv-operator.clusterserviceversion.yaml > _tmp/bundle_deployment.yaml
        yq '.spec' helm/templates/deployment.yaml > _tmp/helm_deployment.yaml
        diff <(yq -P _tmp/bundle_deployment.yaml) <(yq -P _tmp/helm_deployment.yaml)
