name: Build and push to quay.io
on:
  push:
    branches: [ main, release-*, workflow-test ]

env:
  WF_REGISTRY_USER: netobserv+github_ci
  WF_REGISTRY: quay.io/netobserv
  WF_IMAGE: network-observability-operator
  WF_ORG: netobserv
  WF_MULTIARCH_TARGETS: amd64 arm64 ppc64le s390x
  WF_VERSION: ${{ github.ref_name }}

jobs:
  update-newtag-in-helm-chart:
    name: update image version in helm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update image version in deployment file
      run: |
        sed -i '/netobserv:/,/^[^ ]/s/version: .*/version: "${{ env.WF_VERSION }}"/' helm/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "jtakvori@redhat.com"
        git config --global user.name "jotak"
        touch tmp
        git add tmp
        git commit -m "Updated image version in values.yaml"
        git remote -v
        git log
        git push origin HEAD:test
